### ISSUE TITLE
change class names

### ISSUE THREAD

**Issue by RoniMili** [hadasarik/randomeal#1]
Hi! The extension isn't working as it is now- I made some changes in the content file and it seems to be working now.

`const getRandomeal = () => {
    const restaurants = document.querySelectorAll("div[class^='RestaurantItem__Root']")
    const openRestaurants = Array.from(restaurants).filter(
        rest => rest.querySelectorAll("div[class^='ClosedRestaurant__Root-sc-oblu30-0 vjJXS']").length === 0
    )

    if (openRestaurants.length) {
        const randomRestaurantIndex = Math.floor(Math.random() * openRestaurants.length)
        openRestaurants[randomRestaurantIndex].click()
    } else {
        window.alert("Cannot find any open restaurants :(\n" +
            "Try going to the main page. If you're already there, try again later.");
    }
}
`

**Comment by hadasarik** [comment]
Thanks @RoniMili! Just got around to fixing this, since my company moved to Cibus :P
